In [1]:
import numpy as np

In [2]:
np.arange(1.11,10.33)

array([ 1.11,  2.11,  3.11,  4.11,  5.11,  6.11,  7.11,  8.11,  9.11,
       10.11])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
arr=np.random.rand(3,4)

In [15]:
arr

array([[0.99692376, 0.18118349, 0.49935514, 0.60513315],
       [0.10980766, 0.93696209, 0.29557961, 0.30333619],
       [0.54409342, 0.21503762, 0.90333159, 0.9939503 ]])

In [29]:
l=[[1,2,3,4],[5,6,7,8]]

In [30]:
type(l)

list

In [31]:
arr=np.array(l)

In [32]:
type(arr)

numpy.ndarray

In [33]:
np.ndim(arr)

2

In [34]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
np.diag(arr)

array([1, 6])

In [37]:
np.roll(arr,2,axis=1)

array([[3, 4, 1, 2],
       [7, 8, 5, 6]])

In [39]:
a=5
print(~a)

-6


In [43]:
sin_arr=np.sin(arr)

In [46]:
sin_arr

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [44]:
cos_arr=np.cos(arr)

In [47]:
cos_arr

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

In [45]:
sin_arr**2 + cos_arr**2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
a=3
b=a
b=b+1
print(b,a)

4 3


In [49]:
c=np.copy(a)

In [52]:
np.zeros(2)


array([0., 0.])

In [53]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [56]:
arr [0][1]=1

In [57]:
arr

array([[1, 1, 3, 4],
       [5, 6, 7, 8]])

In [58]:
 np.unique(arr)

array([1, 3, 4, 5, 6, 7, 8])

In [62]:
np.power(arr,arr)

array([[       1,        1,       27,      256],
       [    3125,    46656,   823543, 16777216]])

In [63]:
np.flip(arr)

array([[8, 7, 6, 5],
       [4, 3, 1, 1]])

In [64]:
arr

array([[1, 1, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.argsort(arr)

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)